### ISSUE TITLE
Can't set yaw between 90 and 270

### ISSUE THREAD

**Issue by tracygardner** [trinketapp/3D-testing#10]
In the new 3D UI I can't drag the Sense HAT to yaw values between 90 and 270.

**Comment by davidhoness** [comment]
Yeah, this kind of prevents it being used like a compass.

**Comment by eah13** [comment]
Thanks for the report!  We're discussing a solution.

**Comment by davidhoness** [comment]
@tracygardner can you re-test?

**Comment by eah13** [comment]
Closing for now.  Please comment or reopen if this is still reproducible after a refresh of open pages.
