### ISSUE TITLE
Yaw (and Compass) when flipping Sense HAT

### ISSUE THREAD

**Issue by tracygardner** [trinketapp/3D-testing#11]
get_compass is tied to yaw. (Not sure if this is still an issue in the new UI as there's another issue with yaw.)

If we flip the Sense HAT 180 in the pitch and roll orientations then the Sense HAT is 'upside down' so I'd expect it to be rotated 180 via yaw (and therefore facing South) but it reports North. 

![image](https://cloud.githubusercontent.com/assets/14887827/24542333/2af0f156-15f3-11e7-8039-67edbd96b550.png)

**Comment by eah13** [comment]
Thanks for reporting! This is indeed a bug in our IMU implementation.  Looking into it now.

**Comment by davidhoness** [comment]
@tracygardner can you re-test?

**Comment by eah13** [comment]
This is fixed in production

![screenshot 2017-04-14 at 10 07 18 am](https://cloud.githubusercontent.com/assets/1702745/25045440/67501c28-20fa-11e7-93ee-7229176e4abf.png)
