### ISSUE TITLE
Default rotation for old trinkets is now wrong

### ISSUE THREAD

**Issue by davidhoness** [trinketapp/3D-testing#13]
It looks like the compass fix to ensure that geomagnetic North is at the top of the screen has caused a rotation problem for old trinkets.

Old trinkets now show with the Sense HAT inverted.
Example here: https://trinket.io/embed/python/308a373b5c
Which is used in this educational resource: https://www.raspberrypi.org/learning/getting-started-with-the-sense-hat/worksheet/

![def1](https://cloud.githubusercontent.com/assets/6640424/24948065/019f708a-1f61-11e7-9ec3-9a89ac045d98.png)

Currently a manual fix for this is to load the trinket, reset it and re-share it to get a new ID. Since we have the Sense HAT trinket embedded into a lot of our resources and in many places it's preferable if this can be fixed in software meaning no manual intervention required.

The fix for this should also not affect trinkets which have been reset and re-shared already, some of the Code Club resources have done the manual fix.

**Comment by eah13** [comment]
Fix on the way for this...

**Comment by eah13** [comment]
Fix is deployed! Feel free to re-open if this isn't fixed after a refresh.

No code changes needed to old-style trinkets.  Also, the re-shared trinkets should all load using their new position settings, so no further changes needed.
