### ISSUE TITLE
Change of font size moves the 3D model

### ISSUE THREAD

**Issue by davidhoness** [trinketapp/3D-testing#14]
A change of font size moves the position of the 3D model, it happens with the menu and also with browser hot keys.

Steps to reproduce:

- Position the model at an oblique angle
  ![a](https://cloud.githubusercontent.com/assets/6640424/24948278/ba3f3ecc-1f61-11e7-8689-7df4149f2e84.png)
- Open the menu
  ![b](https://cloud.githubusercontent.com/assets/6640424/24948288/c038fb6a-1f61-11e7-9fc3-38b8cdebb469.png)
- Choose any font size
- The model position has changed
  ![c](https://cloud.githubusercontent.com/assets/6640424/24948291/c24299ac-1f61-11e7-9eb6-274911a02f1b.png)

The only way to change the model position should be through direct mouse input.

**Comment by eah13** [comment]
Fix is deployed! Feel free to re-open if this isn't fixed after a refresh.  The model's zoom still changes alongside font size but we left that in for now since presumably in a presentation situation it's helpful.
