### ISSUE TITLE
Moving central drag-bar moves the 3D model

### ISSUE THREAD

**Issue by davidhoness** [trinketapp/3D-testing#15]
Possibly related to #14 

When the central drag-bar is moved, the position of the 3D model is either reset or changes.

Steps to reproduce:

- Move the model to an oblique angle
  ![d](https://cloud.githubusercontent.com/assets/6640424/24948689/08cdac30-1f63-11e7-8bf0-a6dbba3fdacd.png)
- Move the central drag-bar slightly
- The model is either reset or changes position
  ![e](https://cloud.githubusercontent.com/assets/6640424/24948692/0a570254-1f63-11e7-9fec-3a63b6f7dcbb.png)
- The pitch, roll and yaw labels do not update

The only way to change the model position should be through direct mouse input.

**Comment by eah13** [comment]
Thanks.

Note: this seems related to #14 since they both change font size.

**Comment by eah13** [comment]
Fix is deployed! Feel free to re-open if this isn't fixed after a refresh.
