### ISSUE TITLE
 FireFox User-Agent detection in Embedded trinkets 

### ISSUE THREAD

**Issue by davidhoness** [trinketapp/3D-testing#22]
Found an embedded trinket where FireFox gets the 3D model as opposed to the 2D one.
Example here: https://codeclubprojects.org/en-GB/sense-hat/tightrope/

**Comment by eah13** [comment]
Reproduced on this and [other trinkets](https://codeclubprojects.org/en-GB/sense-hat/compass-maze/) embedded on codeclubprojects.org.  Will have to look into this.  ~~I'm unsure exactly how this would happen, but it seems related to the domain the trinket is embedded in.~~  The [RPi blog post](https://www.raspberrypi.org/blog/sense-hat-emulator-upgrade/) is unaffected.

Edit: see below

**Comment by eah13** [comment]
Scratch that: it's related to the `outputOnly=true` query parameter; https://trinket.io/python/e13bde8f93?outputOnly=true

We'll look into a fix.

**Comment by brianpmarks** [comment]
Thanks for this report. Firefox should now be getting the 2D version on these sites. Please reopen if still an issue.
